language: rust
matrix:
  include:
    - rust: stable

script:
  - cargo build --verbose
  - cargo test --verbose --no-default-features
  - cargo test --verbose
  - cargo test --verbose --features percent-encode
  - cargo test --verbose --features secure
  - cargo test --verbose --all-features

notifications:
  email:
    on_success: never
